- name: "Rebuild fonts cache"
  command: "fc-cache"
  become: true

- name: "Start and enable docker service"
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: "Make ZSH default shell"
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  become: true

- name: "Restart i3"
  command: "i3-msg restart"
