- block:

  - name: "Create tempdir"
    tempfile:
      state: directory
    register: tempdir
    check_mode: no
    changed_when: false
  
  - name: "Get starship install script"
    get_url:
      url: "https://raw.githubusercontent.com/starship/starship/master/install/install.sh"
      dest: "{{ tempdir.path }}"
      mode: "0755"
    check_mode: no
    changed_when: false
  
  - name: "Launch starship install script"
    command:
      cmd: "sh install.sh -y"
      chdir: "{{ tempdir.path }}"
      creates: /usr/local/bin/starship

  always:

  - name: "Remove tempdir"
    file:
      path: "{{ tempdir.path }}"
      state: absent
    when: tempdir.path is defined
    check_mode: no
    changed_when: false