- name: Install tools packages
  ansible.builtin.package:
    name: "{{ shell_tools_packages }}"
    state: latest
  become: true

- name: "Install tools archived binaries"
  ansible.builtin.unarchive:
    src: "{{ item.url }}"
    remote_src: yes
    dest: /usr/local/bin
    mode: 0755
    include:
    - "{{ item.name }}"
    creates: "/usr/local/bin/{{ item.name }}"
  loop: "{{ shell_tools_archived_binaries }}"
  become: true

- name: "Setup tools aliases"
  ansible.builtin.lineinfile:
    path: ~/.aliases
    line: "alias {{ item.name }}='{{ item.cmd }}'"
    create: yes
  loop: "{{ shell_tools_aliases }}"