- name: "Add user to docker group"
  user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
    - docker
  become: true

- name: "Refresh apt cache"
  ansible.builtin.apt:
    update_cache: true
  become: true