- name: "Clone dotfiles repository"
  git: 
    repo: "git@github.com:davidcharbonnier/dotfiles.git"
    dest: ~/.dotfiles
    force: yes

- name: "Load symlinks config"
  include_vars:
    file: ~/.dotfiles/config.yml

- name: "Test existing dotfiles presence"
  stat:
    path: "{{ item.dest }}"
  register: stat
  loop: "{{ links }}"

- name: "Remove existing files and dirs"
  file:
    path: "{{ item.item.dest }}"
    state: absent
  when: item.stat.exists and not item.stat.islnk
  loop: "{{ stat.results }}"
  
- name: "Create dotfiles symlinks"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop: "{{ links }}"
  notify: "Restart i3"