- name: "Configure GPG agent"
  copy:
    src: gpg-agent.conf
    dest: ~/.gnupg/gpg-agent.conf

- name: "Configure profile"
  blockinfile:
    path: ~/.profile
    block: |
      GPG_TTY=$(tty)
      export GPG_TTY
      if [ -z "$GPG_AGENT_INFO" ]; then
        eval "$(gpg-agent --daemon --options ~/.gnupg/gpg-agent.conf)"
      fi

      if [ -z "$SSH_AUTH_SOCK" ]; then
        SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
        export SSH_AUTH_SOCK
      fi

- name: "Check for Gnome Keyring installation"
  command:
    cmd: "rpm -qa gnome-keyring"
  become: true
  register: keyring

- name: "Disable Gnome Keyring"
  blockinfile:
    path: /etc/xdg/autostart/gnome-keyring-ssh.desktop
    block: |
      Hidden=true
      X-GNOME-Autostart-enabled=false
  become: true
  when: keyring.stdout