- name: "Install krew"
  block:

  - name: "Create tempdir"
    tempfile:
      state: directory
    register: tempdir
    check_mode: no
    changed_when: false
  
  - name: "Download files"
    get_url:
      url: "https://github.com/kubernetes-sigs/krew/releases/latest/download/{{ item }}"
      dest: "{{ tempdir.path }}"
    loop:
    - krew.tar.gz
    - krew.yaml
    check_mode: no
    changed_when: false

  - name: "Extract archive"
    unarchive:
      src: "{{ tempdir.path }}/krew.tar.gz"
      dest: "{{ tempdir.path }}"
      remote_src: yes
    check_mode: no
    changed_when: false
  
  - name: "Install krew"
    command:
      cmd: "./krew-linux_amd64 install --manifest=krew.yaml --archive=krew.tar.gz"
      chdir: "{{ tempdir.path }}"
  
  always:

  - name: "Remove tempdir"
    file:
      path: "{{ tempdir.path }}"
      state: absent
    when: tempdir.path is defined
    check_mode: no
    changed_when: false

- name: "Update krew"
  command:
    cmd: "kubectl krew upgrade"

- name: "Update krew index"
  command:
    cmd: "kubectl krew system receipts-upgrade"

- name: "Install kubectl plugins"
  command:
    cmd: "kubectl krew install {{ item }}"
  loop: "{{ laptop_kubectl_plugins }}"