- name: "Clone password store repo"
  git: 
    repo: "git@github.com:davidcharbonnier/pass.git"
    dest: ~/.password-store
    force: yes

- name: "Test password store"
  command: "pass ls"
  check_mode: no
  changed_when: false