- name: "Install static software (1/3)"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop: "{{ laptop_static_binary_software }}"
  become: true

- name: "Install static software (2/3)"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ laptop_static_binary_software_scripts }}"
  become: true

- name: "Install static software (3/3)"
  debug:
    msg: "Download & extract to right location"