- name: Install rpm package repo
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    file: kubernetes
    baseurl: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/"
    gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
  become: true
  when: ansible_os_family == "RedHat"

- name: Install deb package repos
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
  become: true
  loop: "{{ kubernetes_apt_repos }}"
  when: ansible_os_family == "Debian"
  notify: "Refresh apt cache"

- ansible.builtin.meta: flush_handlers

- name: Install packages
  ansible.builtin.package:
    name: "{{ kubernetes_packages }}"
    state: latest
  become: true

- name: "Install binaries"
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{ item.name }}"
    mode: 0755
  loop: "{{ kubernetes_binaries }}"
  become: true