kubernetes_version: v1.29
kubernetes_packages:
- kubectl
- helm
kubernetes_kubectl_plugins:
- ctx
- ns
- get-all
kubernetes_apt_repos:
- name: kubernetes
  uris: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/
  suites: /
  components: null
  signed_by: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key
- name: helm
  uris: https://baltocdn.com/helm/stable/debian/
  suites: all
  components: main
  signed_by: https://baltocdn.com/helm/signing.asc
kubernetes_binaries:
- name: kind
  url: https://github.com/kubernetes-sigs/kind/releases/latest/download/kind-linux-amd64
kubernetes_aliases:
- name: ktx
  cmd: kubectl ctx
- name: kns
  cmd: kubectl ns
- name: krr
  cmd: docker run --rm -ti robustadev/krr:v1.16.0 python krr.py
- name: k9s
  cmd: docker run --rm -it -v ~/.kube/config:/root/.kube/config -v ~/.config/k9s:/root/.config/k9s derailed/k9s