- name: Install rpm package repo
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    file: docker-ce
    baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/$releasever/$basearch/stable"
    gpgcheck: yes
    gpgkey: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  become: true
  when: ansible_os_family == "RedHat"

- name: Install deb package repo
  ansible.builtin.deb822_repository:
    name: docker
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release }}"
    components: stable
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  become: true
  when: ansible_os_family == "Debian"
  notify: "Refresh apt cache"

- ansible.builtin.meta: flush_handlers

- name: Install packages
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: latest
  become: true
  notify: "Add user to docker group"

- name: Enable and start service
  ansible.builtin.systemd_service:
    name: docker
    daemon_reload: true
    enabled: true
    state: started
  become: true